package view;

import control.ControleProduto;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Produtos;


public class ConsultaProduto extends javax.swing.JFrame {

    ControleProduto ctrlProduto;

    DefaultTableModel dados;

    public ConsultaProduto() {
        initComponents();
        ctrlProduto = new ControleProduto();
        dados = (DefaultTableModel) tbtBusca.getModel();
    }

    public void limpa(){
        txtCodigo.setText("");
        txtEditora.setText("");
        txtTitulo.setText("");
        txtAutor.setText("");
        jFPreco.setValue(null);
        jCGenero.setSelectedIndex(0);
        dados.setNumRows(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtBusca = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEditora = new javax.swing.JTextField();
        jCGenero = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jFPreco = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnExcuir = new javax.swing.JToggleButton();
        btnAtualizar = new javax.swing.JToggleButton();
        btnLimpar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Livros");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        tbtBusca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbtBusca.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Cod", "Título", "Autor", "Genero", "Editora", "Valor"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbtBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtBuscaMouseClicked(evt);
            }
        });
        tbtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbtBuscaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbtBusca);
        if (tbtBusca.getColumnModel().getColumnCount() > 0) {
            tbtBusca.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbtBusca.getColumnModel().getColumn(1).setPreferredWidth(180);
            tbtBusca.getColumnModel().getColumn(2).setPreferredWidth(120);
            tbtBusca.getColumnModel().getColumn(3).setPreferredWidth(100);
            tbtBusca.getColumnModel().getColumn(4).setPreferredWidth(100);
            tbtBusca.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        btnPesquisar.setForeground(new java.awt.Color(153, 153, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/accept.png"))); // NOI18N
        btnPesquisar.setText("  Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Título:");

        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("Autor:  ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Código: ");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Editora: ");

        jCGenero.setForeground(new java.awt.Color(153, 153, 255));
        jCGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gênero", "Romance", "Ficção", "Tragédia", "Comédia" }));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Preço Unitário:");

        jFPreco.setForeground(new java.awt.Color(153, 153, 255));
        jFPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jFPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFPrecoFocusLost(evt);
            }
        });
        jFPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtEditora))
                                                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(48, 48, 48)
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(33, 33, 33)
                                                                .addComponent(jCGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(19, 19, 19)
                                                                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel)
                                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel6)
                                                .addComponent(jFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jCGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Consulta de Livros");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExcuir.setForeground(new java.awt.Color(153, 153, 255));
        btnExcuir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel.png"))); // NOI18N
        btnExcuir.setText("    Excluir");
        btnExcuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcuirActionPerformed(evt);
            }
        });

        btnAtualizar.setForeground(new java.awt.Color(153, 153, 255));
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book_next.png"))); // NOI18N
        btnAtualizar.setText(" Atualizar");
        btnAtualizar.setActionCommand("Limpar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnLimpar.setForeground(new java.awt.Color(153, 153, 255));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/application.png"))); // NOI18N
        btnLimpar.setText("    Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                                                        .addComponent(btnExcuir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(btnAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(btnLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jScrollPane1)
                                                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnExcuir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {
        int cod = 0;
        if(!("".equals(txtCodigo.getText()))){
            cod = Integer.parseInt(txtCodigo.getText());
        }
        String editora = txtEditora.getText();
        String titulo = txtTitulo.getText();
        String autor = txtAutor.getText();
        float preco = 0;
        if(!("".equals(jFPreco.getText()))){
            preco = Float.parseFloat(jFPreco.getText().replace("R$", "").replace(" ", "").replace(".", "").replace(",", "."));
        }
        int genero = jCGenero.getSelectedIndex();

        dados.setNumRows(0);

        //declarando uma variável do tipo moeda aceito
        BigDecimal valor = new BigDecimal(preco);

        //criando uma variável NumberFormat para inserir o tipo de moeda local (R$ ##,##)
        NumberFormat valor2 = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));

        if(cod == 0 && ("".equals(editora)) && ("".equals(titulo)) && ("".equals(autor)) && preco == 0 && (genero == 0)){
            try{
                ArrayList lista = ctrlProduto.buscarProduto();
                Iterator it = lista.iterator();
                while(it.hasNext()){
                    Produtos prod = (Produtos) it.next();
                    dados.addRow(new Object[]{prod.getCod_prod(), prod.getTitulo(), prod.getAutor(), prod.getGenero(), prod.getEditora(), valor2.format(prod.getPrecoUni())});
                }
            }catch(SQLException ex){
                ex.printStackTrace();
            }
        }else{
            if(cod > 0){
                String x = Integer.toString(cod);
                try{
                    ArrayList lista = ctrlProduto.buscarProduto("cod_produto", x);
                    Iterator it = lista.iterator();
                    while(it.hasNext()){
                        Produtos prod = (Produtos) it.next();
                        dados.addRow(new Object[]{prod.getCod_prod(), prod.getTitulo(), prod.getAutor(), prod.getGenero(), prod.getEditora(), valor2.format(prod.getPrecoUni())});
                    }
                }catch(SQLException ex){
                    ex.printStackTrace();
                }
            }
            if(!("".equals(editora))){
                try{
                    ArrayList lista = ctrlProduto.buscarProduto("editora", editora);
                    Iterator it = lista.iterator();
                    while(it.hasNext()){
                        Produtos prod = (Produtos) it.next();
                        dados.addRow(new Object[]{prod.getCod_prod(), prod.getTitulo(), prod.getAutor(), prod.getGenero(), prod.getEditora(), valor2.format(prod.getPrecoUni())});
                    }
                }catch(SQLException ex){
                    ex.printStackTrace();
                }
            }
            if(!("".equals(titulo))){
                try{
                    ArrayList lista = ctrlProduto.buscarProduto("titulo", titulo);
                    Iterator it = lista.iterator();
                    while(it.hasNext()){
                        Produtos prod = (Produtos) it.next();
                        dados.addRow(new Object[]{prod.getCod_prod(), prod.getTitulo(), prod.getAutor(), prod.getGenero(), prod.getEditora(), valor2.format(prod.getPrecoUni())});
                    }
                }catch(SQLException ex){
                    ex.printStackTrace();
                }
            }
            if(!("".equals(autor))){
                try{
                    ArrayList lista = ctrlProduto.buscarProduto("autor", autor);
                    Iterator it = lista.iterator();
                    while(it.hasNext()){
                        Produtos prod = (Produtos) it.next();
                        dados.addRow(new Object[]{prod.getCod_prod(), prod.getTitulo(), prod.getAutor(), prod.getGenero(), prod.getEditora(), valor2.format(prod.getPrecoUni())});
                    }
                }catch(SQLException ex){
                    ex.printStackTrace();
                }
            }
            if(preco > 0){
                String x = Float.toString(preco);
                try{
                    ArrayList lista = ctrlProduto.buscarProduto("precoUni", x);
                    Iterator it = lista.iterator();
                    while(it.hasNext()){
                        Produtos prod = (Produtos) it.next();
                        dados.addRow(new Object[]{prod.getCod_prod(), prod.getTitulo(), prod.getAutor(), prod.getGenero(), prod.getEditora(), valor2.format(prod.getPrecoUni())});
                    }
                }catch(SQLException ex){
                    ex.printStackTrace();
                }
            }
            if(genero > 0){
                String gen = jCGenero.getItemAt(genero);
                try{
                    ArrayList lista = ctrlProduto.buscarProduto("genero", gen);
                    Iterator it = lista.iterator();
                    while(it.hasNext()){
                        Produtos prod = (Produtos) it.next();
                        dados.addRow(new Object[]{prod.getCod_prod(), prod.getTitulo(), prod.getAutor(), prod.getGenero(), prod.getEditora(), valor2.format(prod.getPrecoUni())});
                    }
                }catch(SQLException ex){
                    ex.printStackTrace();
                }
            }
        }
    }

    private void btnExcuirActionPerformed(java.awt.event.ActionEvent evt) {
        int linha = tbtBusca.getSelectedRow();

        if(linha != -1){
            boolean excluiu = false;
            int cod = Integer.parseInt(tbtBusca.getValueAt(linha, 0).toString());
            try{
                excluiu = ctrlProduto.excluirProduto(cod);
            }catch(SQLException ex){
                ex.printStackTrace();
            }
            if(excluiu){
                JOptionPane.showMessageDialog(null, "Excluído com sucesso!");
                limpa();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um item para ser removido!");
        }
    }

    private void jFPrecoFocusLost(java.awt.event.FocusEvent evt) {
        //declarando uma variável e pegando o valor da tela
        String valor = jFPreco.getText().replace(",", ".");

        if(!"".equals(valor)){
            //declarando uma variável do tipo moeda aceito
            BigDecimal valor2 = new BigDecimal(valor);

            //criando uma variável NumberFormat para inserir o tipo de moeda local (R$ ##,##)
            NumberFormat valor3 = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));

            //criando uma variável para enviar para a tela
            String valorFormatado = valor3.format(valor2);
            jFPreco.setText(valorFormatado);
        }else{
            jFPreco.setValue(null);
        }
    }

    private void jFPrecoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {
        int linha = tbtBusca.getSelectedRow();

        if(linha != -1){
            boolean atualizou = false;
            int cod = Integer.parseInt(tbtBusca.getValueAt(linha, 0).toString());
            int y = jCGenero.getSelectedIndex();
            try{
                atualizou = ctrlProduto.atualizarProduto(Integer.parseInt(txtCodigo.getText()), txtTitulo.getText(), txtAutor.getText(), jCGenero.getItemAt(y), txtEditora.getText(), Float.parseFloat(jFPreco.getText().replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".")));
            }catch(SQLException ex){
                ex.printStackTrace();
            }
            if(atualizou){
                JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso!", "Atualização", JOptionPane.INFORMATION_MESSAGE);
                limpa();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione o item a ser atualizado!", "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {
        limpa();
    }

    private void tbtBuscaKeyPressed(java.awt.event.KeyEvent evt) {

    }

    private void tbtBuscaMouseClicked(java.awt.event.MouseEvent evt) {
        int linha = tbtBusca.getSelectedRow();
        if (linha > -1) {
            txtCodigo.setText(dados.getValueAt(linha, 0).toString());
            txtEditora.setText(dados.getValueAt(linha, 4).toString());
            txtTitulo.setText(dados.getValueAt(linha, 1).toString());
            txtAutor.setText(dados.getValueAt(linha, 2).toString());
            jFPreco.setText(dados.getValueAt(linha, 5).toString());

            String x = dados.getValueAt(linha, 3).toString();

            if("Genero".equals(x)) jCGenero.setSelectedIndex(0);
            if("Romance".equals(x)) jCGenero.setSelectedIndex(1);
            if("Ficção".equals(x)) jCGenero.setSelectedIndex(2);
            if("Tragédia".equals(x)) jCGenero.setSelectedIndex(3);
            if("Comédia".equals(x)) jCGenero.setSelectedIndex(4);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JToggleButton btnAtualizar;
    private javax.swing.JToggleButton btnExcuir;
    private javax.swing.JToggleButton btnLimpar;
    private javax.swing.JToggleButton btnPesquisar;
    private javax.swing.JComboBox<String> jCGenero;
    private javax.swing.JFormattedTextField jFPreco;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtBusca;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration
}
